// eslint-disable-next-line @typescript-eslint/no-var-requires
const caniuse = require("caniuse-api");
import { FontFormat } from "./types";
import browserslist from "browserslist";
import fs from "fs";


export const getMapping = (): Record<FontFormat, Record<string, boolean>> => {
    const browsersList = browserslist("> 0%").reverse();

    return browsersList.reduce((acc: Record<FontFormat, Record<string, boolean>>, val: string) => {
        if (caniuse.isSupported("svg-fonts", val)) {
            acc.svg[val] = true;
        }
        if (caniuse.isSupported("ttf", val)) {
            acc.ttf[val] = true;
        }
        if (caniuse.isSupported("eot", val)) {
            acc.eot[val] = true;
        }
        if (caniuse.isSupported("woff", val)) {
            acc.woff[val] = true;
        }
        if (caniuse.isSupported("woff2", val)) {
            acc.woff2[val] = true;
        }

        return acc;
    }, {
        svg: {},
        ttf: {},
        eot: {},
        woff: {},
        woff2: {},
    });
};

export const generate = () => {
    fs.writeFileSync("src/data.ts", `// generated by generate.ts
import { FontFormat } from "./types";
const data: Record<FontFormat, Record<string, boolean>> = ${JSON.stringify(getMapping(), null, 2)};
export default data;
`);
};
